CREATE PROCEDURE `GET_GROUPS`(IN `ROOM_ID` INT UNSIGNED
) BEGIN
	SELECT * FROM `GROUPS` WHERE `ROOM_ID` = `ROOM_ID`;
END;

CREATE PROCEDURE `ADD_GROUP`(IN `ROOM_ID` INT UNSIGNED
, IN `CREATOR_ID` INT UNSIGNED, IN `NAME` VARCHAR(
32), IN `MAIN_COLOR` VARCHAR(7), IN `SECONDARY_COLOR`
VARCHAR(7)) BEGIN
	SELECT `NAME`, `MAIN_COLOR`;
	INSERT INTO
	    `GROUPS`(
	        `ROOM_ID`,
	        `CREATOR_ID`,
	        `NAME`,
	        `MAIN_COLOR`,
	        `SECONDARY_COLOR`
	    )
	VALUES (
	        `ROOM_ID`,
	        `CREATOR_ID`,
	        `NAME`,
	        `MAIN_COLOR`,
	        `SECONDARY_COLOR`
	    );
END;

CREATE PROCEDURE `UPDATE_GROUP_NAME`(IN `GROUP_ID`
INT UNSIGNED, IN `NAME`VARCHAR(32)) BEGIN
	UPDATE `GROUPS` SET `NAME` = `NAME` WHERE `ID` = `GROUP_ID`;
END;

CREATE PROCEDURE `UPDATE_GROUP_MAIN_COLOR`(IN `GROUP_ID`
INT UNSIGNED, IN `MAIN_COLOR`VARCHAR(7)) BEGIN
	UPDATE `GROUPS`
	SET `MAIN_COLOR` = `MAIN_COLOR`
	WHERE `ID` = `GROUP_ID`;
END;

CREATE PROCEDURE `UPDATE_GROUP_SECONDARY_COLOR`(IN
`GROUP_ID` INT UNSIGNED, IN `SECONDARY_COLOR`VARCHAR
(7)) BEGIN
	UPDATE `GROUPS`
	SET
	    `SECONDARY_COLOR` = `SECONDARY_COLOR`
	WHERE `ID` = `GROUP_ID`;
END;

CREATE PROCEDURE `REMOVE_GROUP`(IN `GROUP_ID` INT UNSIGNED
) BEGIN
	DELETE FROM `GROUPS` WHERE `ID` = `GROUP_ID`;
END;
