CREATE PROCEDURE `INSERT_COMMENT`(IN `TASK_ID` INT 
UNSIGNED, IN `AUTHOR_ID` INT UNSIGNED, IN `CONTENT` 
VARCHAR(128)) BEGIN 
	INSERT INTO
	    `COMMENTS`(
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    )
	VALUES (
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    );
END; 

CREATE PROCEDURE `UPDATE_COMMENT_CONTENT`(IN `TASK_ID` 
INT UNSIGNED, IN `AUTHOR_ID` INT UNSIGNED, IN `CONTENT` 
VARCHAR(128)) BEGIN 

END; 