CREATE PROCEDURE `GET_COMMENTS`(IN `TASK_ID` INT UNSIGNED
) BEGIN
	SELECT * FROM `COMMENTS` WHERE `TASK_ID` = `TASK_ID`;
END;

CREATE PROCEDURE `ADD_COMMENT`(IN `TASK_ID` INT UNSIGNED
, IN `AUTHOR_ID` INT UNSIGNED, IN `CONTENT` VARCHAR
(128)) BEGIN
	INSERT INTO
	    `COMMENTS`(
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    )
	VALUES (
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    );
END;

CREATE PROCEDURE `UPDATE_COMMENT_CONTENT`(IN `TASK_ID`
INT UNSIGNED, IN `CONTENT` VARCHAR(128)) BEGIN
	UPDATE `COMMENTS`
	SET `CONTENT` = `CONTENT`
	WHERE `TASK_ID` = `TASK_ID`;
END;

CREATE PROCEDURE `REMOVE_COMMENT`(IN `COMMENT_ID` INT
UNSIGNED) BEGIN
	DELETE FROM `COMMENTS` WHERE `ID` = `COMMENT_ID`;
END;
