CREATE PROCEDURE `GET_COMMENTS`(IN `TASK_ID` INT UNSIGNED
) BEGIN
	SELECT
	    `COMMENTS`.*,
	    `USERS`.`LOGIN` as `AUTHOR_LOGIN`,
	    `USERS`.`PHOTO` as `AUTHOR_PHOTO`
	FROM `COMMENTS`
	    JOIN `USERS` ON `USERS`.`ID` = `COMMENTS`.`AUTHOR_ID`
	WHERE
	    `COMMENTS`.`TASK_ID` = `TASK_ID`;
END;

CREATE PROCEDURE `ADD_COMMENT`(IN `TASK_ID` INT UNSIGNED
, IN `AUTHOR_ID` INT UNSIGNED, IN `CONTENT` VARCHAR
(128)) BEGIN
	INSERT INTO
	    `COMMENTS`(
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    )
	VALUES (
	        `TASK_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`
	    );
END;

CREATE PROCEDURE `UPDATE_COMMENT_CONTENT`(IN `ID` INT
UNSIGNED, IN `CONTENT` VARCHAR(128)) BEGIN
	UPDATE `COMMENTS`
	SET
	    `COMMENTS`.`CONTENT` = `CONTENT`
	WHERE `COMMENTS`.`ID` = `ID`;
END;

CREATE PROCEDURE `REMOVE_COMMENT`(IN `COMMENT_ID` INT
UNSIGNED) BEGIN
	DELETE FROM `COMMENTS` WHERE `COMMENTS`.`ID` = `COMMENT_ID`;
END;
