CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `COMMENTS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `TASK_ID` INT UNSIGNED NOT NULL,
        `AUTHOR_ID` INT UNSIGNED NOT NULL,
        `CONTENT` VARCHAR(128) NOT NULL CHECK(LENGTH(`CONTENT`) != 0),
        `CREATED_AT` DATETIME NOT NULL DEFAULT NOW(),
        FOREIGN KEY (`TASK_ID`) REFERENCES `TASKS`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (`AUTHOR_ID`) REFERENCES `USERS`(`ID`)
    );
