CREATE PROCEDURE `GET_TASKS`(IN `ROOM_ID` INT UNSIGNED
) BEGIN
	SELECT
	    `TASKS`.*,
	    `USERS`.`LOGIN` as `AUTHOR_LOGIN`,
	    `USERS`.`PHOTO` as `AUTHOR_PHOTO`
	FROM `TASKS`
	    JOIN `USERS` ON `USERS`.`ID` = `TASKS`.`AUTHOR_ID`
	WHERE
	    `TASKS`.`ROOM_ID` = `ROOM_ID`;
END;

CREATE PROCEDURE `GET_TASK`(IN `ROOM_ID` INT UNSIGNED
, IN `TASK_ID` INT UNSIGNED) BEGIN
	SELECT
	    `TASKS`.*,
	    `USERS`.`LOGIN` as `AUTHOR_LOGIN`,
	    `USERS`.`PHOTO` as `AUTHOR_PHOTO`
	FROM `TASKS`
	    JOIN `USERS` ON `USERS`.`ID` = `TASKS`.`AUTHOR_ID`
	WHERE
	    `TASKS`.`ROOM_ID` = `ROOM_ID`
	    AND `TASKS`.`ID` = `TASK_ID`;
END;

CREATE PROCEDURE `GET_TASKS_PROGRESS`(IN `ROOM_ID`
INT UNSIGNED) BEGIN
	SELECT
	    `TASKS`.`GROUP_ID`,
	    `GROUPS`.`NAME` as `GROUP_NAME`,
	    COUNT(
	        IF(
	            `TASKS`.`STATUS` = 'DONE',
	            `TASKS`.`ID`,
	            NULL
	        )
	    ) as `DONE_COUNT`,
	    COUNT(`TASKS`.`ID`) as `TOTAL_COUNT`
	FROM `TASKS`
	    JOIN `GROUPS` ON `GROUPS`.`ID` = `TASKS`.`GROUP_ID`
	WHERE
	    `TASKS`.`ROOM_ID` = `ROOM_ID`
	GROUP BY `GROUP_ID`;
END;

CREATE PROCEDURE `ADD_TASK`(IN `ROOM_ID` INT UNSIGNED
, IN `GROUP_ID`INT UNSIGNED, IN `AUTHOR_ID` INT UNSIGNED
, IN `CONTENT` VARCHAR(128), IN `STATUS` ENUM('READY'
, 'IN PROGRESS', 'NEED REVIEW', 'DONE')) BEGIN
	INSERT INTO
	    `TASKS`(
	        `ROOM_ID`,
	        `GROUP_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`,
	        `STATUS`
	    )
	VALUES (
	        `ROOM_ID`,
	        `GROUP_ID`,
	        `AUTHOR_ID`,
	        `CONTENT`,
	        `STATUS`
	    );
END;

CREATE PROCEDURE `UPDATE_TASK_STATUS`(IN `TASK_ID`
INT UNSIGNED, IN `STATUS` ENUM('READY', 'IN PROGRESS'
, 'NEED REVIEW', 'DONE')) BEGIN
	UPDATE `TASKS`
	SET
	    `TASKS`.`STATUS` = `STATUS`
	WHERE `TASKS`.`ID` = `TASK_ID`;
END;

CREATE PROCEDURE `UPDATE_TASK_CONTENT`(IN `TASK_ID`
INT UNSIGNED, IN `CONTENT` VARCHAR(128)) BEGIN
	UPDATE `TASKS`
	SET
	    `TASKS`.`CONTENT` = `CONTENT`
	WHERE `TASKS`.`ID` = `TASK_ID`;
END;

CREATE PROCEDURE `UPDATE_TASK_GROUP`(IN `TASK_ID` INT
UNSIGNED, IN `GROUP_ID` INT UNSIGNED) BEGIN
	UPDATE `TASKS`
	SET
	    `TASKS`.`GROUP_ID` = `GROUP_ID`
	WHERE `TASKS`.`ID` = `TASK_ID`;
END;

CREATE PROCEDURE `REMOVE_TASK`(IN `TASK_ID` INT UNSIGNED
) BEGIN
	DELETE FROM `TASKS` WHERE `TASKS`.`ID` = `TASK_ID`;
END;
