CREATE PROCEDURE `INSERT_USER`(IN `LOGIN` VARCHAR(32
), IN `PASSWORD` VARCHAR(255), IN `PHOTO` VARCHAR(
255)) BEGIN 
	INSERT INTO
	    `USERS`(`LOGIN`, `PASSWORD`, `PHOTO`)
	VALUES (`LOGIN`, `PASSWORD`, `PHOTO`);
END; 

CREATE PROCEDURE `GET_USER_BY_LOGIN`(IN `LOGIN` VARCHAR
(32)) BEGIN 
	SELECT * FROM `USERS` WHERE `LOGIN` = `LOGIN`;
END; 