CREATE PROCEDURE `GET_USER_BY_LOGIN`(IN `LOGIN` VARCHAR
(32)) BEGIN
	SELECT * FROM `USERS` WHERE `LOGIN` = `LOGIN`;
END;


CREATE PROCEDURE `ADD_USER`(IN `LOGIN` VARCHAR(32
), IN `PASSWORD` VARCHAR(255), IN `PHOTO` VARCHAR(
255)) BEGIN
	INSERT INTO
	    `USERS`(`LOGIN`, `PASSWORD`, `PHOTO`)
	VALUES (`LOGIN`, `PASSWORD`, `PHOTO`);
END;


CREATE PROCEDURE `UPDATE_USER_PASSWORD`(IN `USER_ID`
INT UNSIGNED, IN `PASSWORD` VARCHAR(255)) BEGIN
	UPDATE `USERS`
	SET `PASSWORD` = `PASSWORD`
	WHERE `ID` = `USER_ID`;
END;

CREATE PROCEDURE `UPDATE_USER_PHOTO`(IN `USER_ID`
INT UNSIGNED, IN `PHOTO` VARCHAR(255)) BEGIN
	UPDATE `USERS`
	SET `PHOTO` = `PHOTO`
	WHERE `ID` = `USER_ID`;
END;
