CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `USERS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `LOGIN` VARCHAR(32) UNIQUE NOT NULL CHECK(LENGTH(`LOGIN`) >= 2),
        `PASSWORD` VARCHAR(255) NOT NULL CHECK(LENGTH(`PASSWORD`) >= 6),
        `PHOTO` VARCHAR(255) NULL
    );
