CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `USERS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `LOGIN` VARCHAR(32) UNIQUE NOT NULL,
        `PASSWORD` VARCHAR(255) NOT NULL,
        `PHOTO` VARCHAR(255) NULL
    );