CREATE PROCEDURE `GET_ACTIVITIES`(IN `ROOM_ID` INT
UNSIGNED) BEGIN
	SELECT
	    `ACTIVITIES`.*,
	    `USERS`.`LOGIN` as `ACTIVIST_LOGIN`,
	    `ACTIVITY_SPHERE`.`NAME` as `SPHERE`
	FROM `ACTIVITIES`
	    JOIN `ACTIVITY_SPHERE` ON `ACTIVITY_SPHERE`.`ID` = `ACTIVITIES`.`SPHERE_ID`
	    JOIN `USERS` ON `USERS`.`ID` = `ACTIVITIES`.`ACTIVIST_ID`
	WHERE
	    `ACTIVITIES`.`ROOM_ID` = `ROOM_ID`
	ORDER BY
	    `ACTIVITIES`.`ID` DESC;
END;
