CREATE PROCEDURE `CREATE_ACTIVITY`(IN `ROOM_ID` INT
UNSIGNED, IN `ACTIVIST_ID` INT UNSIGNED, IN `SPHERE_ID`
INT UNSIGNED, IN `ACTION` ENUM('CREATE', 'UPDATE',
'REMOVE')) BEGIN
	INSERT INTO
	    `ACTIVITIES`(
	        `ROOM_ID`,
	        `ACTIVIST_ID`,
	        `SPHERE_ID`,
	        `ACTION`
	    )
	VALUES (
	        `ROOM_ID`,
	        `ACTIVIST_ID`,
	        `SPHERE_ID`,
	        `ACTION`
	    );
END;

CREATE PROCEDURE `GET_OR_CREATE_ACTIVITY_SPHERE`(IN
`SPHERE_NAME` VARCHAR(32), OUT `SPHERE_ID` INT UNSIGNED
) BEGIN
	IF (
	    not exists(
	        SELECT
	            `ACTIVITY_SPHERE`.`ID`
	        FROM
	            `ACTIVITY_SPHERE`
	        WHERE
	            `ACTIVITY_SPHERE`.`NAME` = `SPHERE_NAME`
	    )
	) THEN
	INSERT INTO
	    `ACTIVITY_SPHERE`(`NAME`)
	VALUES (`SPHERE_NAME`);
	END IF;
	SELECT
	    `ACTIVITY_SPHERE`.`ID` INTO `SPHERE_ID`
	FROM `ACTIVITY_SPHERE`
	WHERE
	    `ACTIVITY_SPHERE`.`NAME` = `SPHERE_NAME`;
END;
