CREATE PROCEDURE `GET_USERS_IN_ROOM`(IN `ROOM_ID` INT
UNSIGNED) BEGIN
	SELECT *
	FROM `USER_ROOM`
	    JOIN `USERS` ON `USERS`.`ID` = `USER_ROOM`.`USER_ID`
	WHERE
	    `ROOM_ID` = `ROOM_ID`
	    AND `DELETED` = FALSE;
END;

CREATE PROCEDURE `GET_USER_ROOMS`(IN `USER_ID` INT
UNSIGNED) BEGIN
	SELECT *
	FROM `USER_ROOM`
	    JOIN `ROOMS` ON `ROOMS`.`ID` = `USER_ROOM`.`ROOM_ID`
	WHERE `USER_ID` = `USER_ID`;
END;

CREATE PROCEDURE `ADD_USER_ROOM`(IN `USER_ID` INT UNSIGNED
, IN `ROOM_ID` INT UNSIGNED) BEGIN
	IF(
	    EXISTS(
	        SELECT `USER_ID`
	        FROM `USER_ROOM`
	        WHERE
	            `USER_ID` = `USER_ID`
	            AND `ROOM_ID` = `ROOM_ID`
	            AND `DELETED` = TRUE
	    )
	) THEN
	UPDATE `USER_ROOM`
	SET `DELETED` = FALSE
	WHERE
	    `USER_ID` = `USER_ID`
	    AND `ROOM_ID` = `ROOM_ID`;
	ELSE
	INSERT INTO
	    `USER_ROOM`(`ROOM_ID`, `USER_ID`)
	VALUES (`ROOM_ID`, `USER_ID`);
	END IF;
END;

CREATE PROCEDURE `REMOVE_USER_ROOM`(IN `USER_ID` INT
UNSIGNED, IN `ROOM_ID` INT UNSIGNED) BEGIN
	UPDATE `USER_ROOM`
	SET `DELETED` = TRUE
	WHERE
	    `USER_ID` = `USER_ID`
	    AND `ROOM_ID` = `ROOM_ID`;
END;
