CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `USER_ROOM`(
        `USER_ID` INT UNSIGNED NOT NULL,
        `ROOM_ID` INT UNSIGNED NOT NULL,
        PRIMARY KEY(`USER_ID`, `ROOM_ID`),
        FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`),
        FOREIGN KEY (`ROOM_ID`) REFERENCES `ROOMS`(`ID`)
    );