CREATE PROCEDURE `GET_ROOM`(IN `ROOM_ID` INT UNSIGNED
) BEGIN
	SELECT * FROM `ROOMS` WHERE `ID` = `ROOM_ID`;
END;

CREATE PROCEDURE `ADD_ROOM`(IN `NAME` VARCHAR(32),
IN `DESCRIPTION` VARCHAR(255)) BEGIN
	INSERT INTO
	    `ROOMS`(`NAME`, `DESCRIPTION`)
	VALUES (`NAME`, `DESCRIPTION`);
END;

CREATE PROCEDURE `UPDATE_ROOM_NAME`(IN `ROOM_ID` INT
UNSIGNED, IN `NAME` VARCHAR(32)) BEGIN
	UPDATE `ROOMS` SET `NAME` = `NAME` WHERE `ROOM_ID` = `ROOM_ID`;
END;

CREATE PROCEDURE `UPDATE_ROOM_DESCRIPTION`(IN `ROOM_ID`
INT UNSIGNED, IN `DESCRIPTION` VARCHAR(32)) BEGIN
	UPDATE `ROOMS`
	SET
	    `DESCRIPTION` = `DESCRIPTION`
	WHERE `ROOM_ID` = `ROOM_ID`;
END;

CREATE PROCEDURE `REMOVE_ROOM`(IN `ROOM_ID` INT UNSIGNED
) BEGIN
	DELETE FROM `ROOMS` WHERE `ROOM_ID` = `ROOM_ID`;
END;
