CREATE PROCEDURE `GET_ROOM_ID_BY_TASK_ID`(IN `TASK_ID` 
INT UNSIGNED, OUT `ROOM_ID_OUT` INT UNSIGNED) BEGIN 
	SELECT
	    `ROOM_ID` INTO `ROOM_ID_OUT`
	FROM `TASKS`
	WHERE `ID` = `TASK_ID`;
END; 