CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `ROOMS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `NAME` VARCHAR(32) NOT NULL,
        `DESCRIPTION` VARCHAR(255) NOT NULL DEFAULT ""
    );