USE `TASKS_MANAGER`;

DROP PROCEDURE
    IF EXISTS `INSERT_USER`
CREATE PROCEDURE
    `INSERT_USER`(
        IN `LOGIN` VARCHAR(32),
        IN `PASSWORD` VARCHAR(255),
        IN `PHOTO` VARCHAR(255) NULL
    ) BEGIN
INSERT INTO
    `USERS`(`LOGIN`, `PASSWORD`, `PHOTO`)
VALUES (@LOGIN, @PASSWORD, @PHOTO);

END;