-- Active: 1669709918752@@127.0.0.1@3306@tasks_manager

CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `USERS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `LOGIN` VARCHAR(32) UNIQUE NOT NULL,
        `PASSWORD` VARCHAR(255) NOT NULL,
        `PHOTO` VARCHAR(255) NULL
    );

CREATE TABLE
    IF NOT EXISTS `ROOMS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `NAME` VARCHAR(32) NOT NULL,
        `DESCRIPTION` VARCHAR(255) NOT NULL DEFAULT ""
    );

CREATE TABLE
    IF NOT EXISTS `USER_ROOM`(
        `USER_ID` INT UNSIGNED NOT NULL,
        `ROOM_ID` INT UNSIGNED NOT NULL,
        PRIMARY KEY(`USER_ID`, `ROOM_ID`),
        FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`),
        FOREIGN KEY (`ROOM_ID`) REFERENCES `ROOMS`(`ID`)
    );

CREATE TABLE
    IF NOT EXISTS `GROUPS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED NOT NULL,
        `CREATOR_ID` INT UNSIGNED NOT NULL,
        `NAME` VARCHAR(32) NOT NULL,
        `MAIN_COLOR` VARCHAR(7) NOT NULL CHECK(
            `MAIN_COLOR` REGEXP "^#[0-9a-fA-F]{6}$"
        ),
        `SECONDARY_COLOR` VARCHAR(7) NOT NULL CHECK(
            `SECONDARY_COLOR` REGEXP "^#[0-9a-fA-F]{6}$"
        ),
        INDEX (`ROOM_ID`),
        FOREIGN KEY (`ROOM_ID`, `CREATOR_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`)
    );

CREATE TABLE
    IF NOT EXISTS `TASKS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED NOT NULL,
        `GROUP_ID` INT UNSIGNED NOT NULL,
        `AUTHOR_ID` INT UNSIGNED NOT NULL,
        `CONTENT` VARCHAR(255) NOT NULL,
        `STATUS` ENUM(
            'READY',
            'IN PROGRESS',
            'NEED REVIEW',
            'DONE'
        ) NOT NULL DEFAULT 'READY',
        `CREATED_AT` DATETIME NOT NULL DEFAULT NOW(),
        FOREIGN KEY (`ROOM_ID`, `GROUP_ID`) REFERENCES `GROUPS`(`ROOM_ID`, `ID`),
        FOREIGN KEY (`ROOM_ID`, `AUTHOR_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`)
    );

CREATE TABLE
    IF NOT EXISTS `COMMENTS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `TASK_ID` INT UNSIGNED NOT NULL,
        `AUTHOR_ID` INT UNSIGNED NOT NULL,
        `CONTENT` VARCHAR(128) NOT NULL,
        `CREATED_AT` DATETIME NOT NULL DEFAULT NOW(),
        FOREIGN KEY (`TASK_ID`) REFERENCES `TASKS`(`ID`),
        FOREIGN KEY (`AUTHOR_ID`) REFERENCES `USERS`(`ID`)
    );

CREATE TABLE
    IF NOT EXISTS `ACTIVITY_SPHERE`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `NAME` VARCHAR(32) UNIQUE NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS `ACTIVITIES`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED NOT NULL,
        `ACTIVIST_ID` INT UNSIGNED NOT NULL,
        `SPHERE_ID` INT UNSIGNED NOT NULL,
        `CREATED_AT` DATETIME NOT NULL DEFAULT NOW(),
        `ACTION` ENUM('Create', 'Update', 'Remove') NOT NULL,
        FOREIGN KEY (`ROOM_ID`, `ACTIVIST_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`),
        FOREIGN KEY (`SPHERE_ID`) REFERENCES `ACTIVITY_SPHERE`(`ID`)
    );