CREATE DATABASE IF NOT EXISTS `TASKS_MANAGER`;

USE `TASKS_MANAGER`;

CREATE TABLE
    IF NOT EXISTS `USERS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `LOGIN` VARCHAR(32) unique,
        `PASSWORD` VARCHAR(255),
        `PHOTO` VARCHAR(255) null
    );

CREATE TABLE
    IF NOT EXISTS `ROOMS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `NAME` VARCHAR(32),
        `DESCRIPTION` VARCHAR(255) DEFAULT ""
    );

CREATE TABLE
    IF NOT EXISTS `USER_ROOM`(
        `USER_ID` INT UNSIGNED,
        `ROOM_ID` INT UNSIGNED,
        PRIMARY KEY(`USER_ID`, `ROOM_ID`),
        FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`),
        FOREIGN KEY (`ROOM_ID`) REFERENCES `ROOMS`(`ID`)
    );

CREATE TABLE
    IF NOT EXISTS `GROUPS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED,
        `CREATOR_ID` INT UNSIGNED,
        `NAME` VARCHAR(32),
        `MAIN_COLOR` VARCHAR(7),
        `SECONDARY_COLOR` VARCHAR(7),
        INDEX (`ROOM_ID`),
        FOREIGN KEY (`ROOM_ID`, `CREATOR_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`)
    );

CREATE TABLE
    IF NOT EXISTS `TASKS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED,
        `GROUP_ID` INT UNSIGNED,
        `AUTHOR_ID` INT UNSIGNED,
        `CONTENT` VARCHAR(255),
        `status` ENUM(
            'Ready',
            'In progress',
            'Need review',
            'Done'
        ),
        `CREATED_AT` DATETIME DEFAULT NOW(),
        FOREIGN KEY (`ROOM_ID`, `GROUP_ID`) REFERENCES `GROUPS`(`ROOM_ID`, `ID`),
        FOREIGN KEY (`ROOM_ID`, `AUTHOR_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`)
    );

CREATE TABLE
    IF NOT EXISTS `COMMENTS`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `TASK_ID` INT UNSIGNED,
        `AUTHOR_ID` INT UNSIGNED,
        `CONTENT` VARCHAR(128),
        `CREATED_AT` DATETIME DEFAULT NOW(),
        FOREIGN KEY (`TASK_ID`) REFERENCES `TASKS`(`ID`),
        FOREIGN KEY (`AUTHOR_ID`) REFERENCES `USERS`(`ID`)
    );

CREATE TABLE
    IF NOT EXISTS `ACTIVITY_SPHERE`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `NAME` VARCHAR(32) UNIQUE
    );

CREATE TABLE
    IF NOT EXISTS `ACTIVITIES`(
        `ID` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        `ROOM_ID` INT UNSIGNED,
        `ACTIVIST_ID` INT UNSIGNED,
        `SPHERE_ID` INT UNSIGNED,
        `CREATED_AT` DATETIME DEFAULT NOW(),
        `ACTION` ENUM('Create', 'Update', 'Remove'),
        FOREIGN KEY (`ROOM_ID`, `ACTIVIST_ID`) REFERENCES `USER_ROOM`(`ROOM_ID`, `USER_ID`),
        FOREIGN KEY (`SPHERE_ID`) REFERENCES `ACTIVITY_SPHERE`(`ID`)
    );