-- Active: 1669709918752@@127.0.0.1@3306@tasks_manager

USE `TASKS_MANAGER`;

DROP TRIGGER IF EXISTS `CREATE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_TASKS_ACTIVITY` AFTER INSERT 
ON `TASKS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_TASKS_ACTIVITY` AFTER UPDATE 
ON `TASKS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_TASKS_ACTIVITY` AFTER DELETE 
ON `TASKS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        OLD.`ROOM_ID`,
	        OLD.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `CREATE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_GROUPS_ACTIVITY` AFTER INSERT 
ON `GROUPS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_GROUPS_ACTIVITY` AFTER UPDATE 
ON `GROUPS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_GROUPS_ACTIVITY` AFTER DELETE 
ON `GROUPS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        OLD.`ROOM_ID`,
	        OLD.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `CREATE_'COMMENTS'_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_'COMMENTS'_ACTIVITY` AFTER INSERT 
ON `COMMENTS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	DECLARE ROOM_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(NEW.`TASK_ID`, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_'COMMENTS'_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_'COMMENTS'_ACTIVITY` AFTER UPDATE 
ON `COMMENTS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	DECLARE ROOM_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(NEW.`TASK_ID`, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END // 


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_'COMMENTS'_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_'COMMENTS'_ACTIVITY` AFTER DELETE 
ON `COMMENTS` FOR EACH ROW BEGIN 
	DECLARE SPHERE_ID INT;
	DECLARE ROOM_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(OLD.TASK_ID, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        OLD.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END // 


DELIMITER ;