-- Active: 1669840403212@@127.0.0.1@3306@TASKS_MANAGER

USE `TASKS_MANAGER`;

DROP TRIGGER IF EXISTS `CREATE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_TASKS_ACTIVITY` AFTER INSERT
ON `TASKS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_TASKS_ACTIVITY` AFTER UPDATE
ON `TASKS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_TASKS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_TASKS_ACTIVITY` AFTER DELETE
ON `TASKS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('TASK', @SPHERE_ID);
	CALL
	    Create_Activity(
	        OLD.`ROOM_ID`,
	        OLD.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `CREATE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_GROUPS_ACTIVITY` AFTER INSERT
ON `GROUPS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_GROUPS_ACTIVITY` AFTER UPDATE
ON `GROUPS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        NEW.`ROOM_ID`,
	        NEW.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_GROUPS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_GROUPS_ACTIVITY` AFTER DELETE
ON `GROUPS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('GROUP', @SPHERE_ID);
	CALL
	    Create_Activity(
	        OLD.`ROOM_ID`,
	        OLD.`CREATOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `CREATE_COMMENTS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `CREATE_COMMENTS_ACTIVITY` AFTER INSERT
ON `COMMENTS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	DECLARE ROOM_ID INT UNSIGNED;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(NEW.`TASK_ID`, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Create'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `UPDATE_COMMENTS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `UPDATE_COMMENTS_ACTIVITY` AFTER UPDATE
ON `COMMENTS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	DECLARE ROOM_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(NEW.`TASK_ID`, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        NEW.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Update'
	    );
	END //


DELIMITER ;

DROP TRIGGER IF EXISTS `REMOVE_COMMENTS_ACTIVITY`;

DELIMITER //

CREATE TRIGGER `REMOVE_COMMENTS_ACTIVITY` AFTER DELETE
ON `COMMENTS` FOR EACH ROW BEGIN
	DECLARE SPHERE_ID INT UNSIGNED;
	DECLARE ROOM_ID INT;
	CALL GET_OR_CREATE_ACTIVITY_SPHERE('COMMENT', @SPHERE_ID);
	CALL GET_ROOM_ID_BY_TASK_ID(OLD.TASK_ID, @ROOM_ID);
	CALL
	    Create_Activity(
	        @ROOM_ID,
	        OLD.`AUTHOR_ID`,
	        @SPHERE_ID,
	        'Remove'
	    );
	END //


DELIMITER ;
